### ISSUE TITLE
Windows Context transparency not working

### ISSUE THREAD

**Issue by LividJava** [ayushhroyy/elegantfox#1]
just reporting this for reference.

Only thing that appears to be working is the background, the context menu items do not appear to support transparency.
![image](https://user-images.githubusercontent.com/7604544/150588642-354c0cb6-0c74-4fa0-a23b-54e5896ece1c.png)

**Comment by ayushhroyy** [comment]
windows is untested as of now [see this from the readme](https://github.com/ayushhroyy/elegantfox#compatibility-status) however, I will try to bring windows and macOS preliminary support in a week or soon

**Comment by LividJava** [comment]
Willing to test if need be

**Comment by LividJava** [comment]
accidentally closed

**Comment by ayushhroyy** [comment]
as of now, I have fixed the transparency issue in the zip css file below, please report if it works for you now also, i see a shadow in the screenshot you have sent, is it a theme issue? it is not appearing on my windows machine (windows 10)
[userChrome.zip](https://github.com/ayushhroyy/elegantfox/files/7919918/userChrome.zip)

**Comment by LividJava** [comment]
Might be? the shadow is still present but transparency is now active, I'm just running the standard dark theme.
![image](https://user-images.githubusercontent.com/7604544/150704394-1e281924-785f-4043-be48-7dad9c06b5d0.png)

**Comment by LividJava** [comment]
yeah i have no idea what could be causing that. apologies

**Comment by ayushhroyy** [comment]
I'll look into this issue, also  do you use windows 10/11 or 7

**Comment by LividJava** [comment]
Using windows 10
![image](https://user-images.githubusercontent.com/7604544/151253448-2f155c12-d419-4e95-aefd-86937de9a228.png)

**Comment by ayushhroyy** [comment]
Hi, if you still use the theme and firefox, I have fixed the issue on my end. please confirm if it runs on your end, this is what the context menu should look like now.
![Screenshot 2024-07-14 094919](https://github.com/user-attachments/assets/8f8c28d4-f4cd-4c4e-93cf-804f10f12fa8)
